### ISSUE TITLE
What about docs? ❤️ 

### ISSUE THREAD

**Issue by mastertech35** [mastertech35/github-projects-playground#6]
Let's work on the documentation with @sarriaga35 suggestions:
- [ ] #7
- [x] #8
- [x] #9
- [ ] Decide if we want to go with something more complex

**Comment by sarriaga35** [comment]
why don't we get started as easily as possible with just a sample docs folder with a single markdown document then turn on GitHub pages and point to it, we can decide if we want to go with something more complex like Jekyll or Eleventy later

**Comment by mastertech35** [comment]
So what you're saying is that we should  

- [ ] Create a `docs` folder
- [ ] Create a new `index.md` document
- [ ] Turn on GitHub Pages
- [ ] Decide if we want to go with sometime more complex

**Comment by mastertech35** [comment]
So what you're saying is that we should 
- [ ] Create a new `index.md` document
- [ ] Create a `docs` folder
- [ ] Turn on GitHub Pages
- [ ] Decide if we want to go with sometime more complex

**Comment by sarriaga35** [comment]
Thanks @sarriaga35 , I created the issues for the first three suggestions, if you think of anything else, let me know.
